name: chatapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutterfire_ui: ^0.3.0
  giphy_picker: ^2.0.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.11
  google_sign_in: ^5.2.4
  xfile: ^1.1.0
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  path_provider: ^2.0.9
  device_info_plus: ^3.2.2
  flutter_keyboard_visibility: ^5.2.0
  fluttertoast: ^8.0.9
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons_maker: "^0.10.1"

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/pc_300.png"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - dotenv
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Koulen
      fonts:
        - asset: fonts/Koulen-Regular.ttf